public class ArithmeticExceptionDemo {
    public static void main(String[] args) {
        try {
            // Divided by Zero
            int result1 = 10 / 0;
        } catch (ArithmeticException e) {
            System.out.println("Error: " + e.getMessage());
        }

        try {
            // Logarithm of negative or Zero
            double result2 = Math.log(0);
        } catch (ArithmeticException e) {
            System.out.println("Error: " + e.getMessage());
        }

        try {
            // Tan 90 Degree
            double result3 = Math.tan(Math.toRadians(90));
        } catch (ArithmeticException e) {
            System.out.println("Error: " + e.getMessage());
        }

        try {
            // Zero power Zero
            double result4 = Math.pow(0, 0);
        } catch (ArithmeticException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
}
